[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  port = 9999
  targetPort = 3000

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200 